### ISSUE TITLE
Does not work with Babel 7

### ISSUE THREAD

**Issue by bebraw** [frontend-collective/react-image-lightbox#101]
I tried consuming the component using Babel 7 beta. It gave the following errors:

```
ERROR in ./node_modules/react-image-lightbox/dist/main.js
Module not found: Error: Can't resolve 'babel-runtime/core-js/json/stringify'

..

ERROR in ./node_modules/react-image-lightbox/dist/main.js
Module not found: Error: Can't resolve 'babel-runtime/helpers/slicedToArray'
```

The build seems to expect `babel-runtime` and installing that fixes the issue. Perhaps that could become a peer dependency so people know to install it or maybe it could be avoided entirely.

**Comment by fritz-c** [comment]
Can you check for me that your node modules directory is exempted from Babel compilation?

**Comment by bebraw** [comment]
Yeah, it is.

I have the entire setup [here](https://github.com/ReactFinland/site). I guess the easiest way to see the problem is to remove `babel-runtime` from the project and build it (`npm run build`).

I can make a tiny repo illustrating the issue too if that's too much.

**Comment by fritz-c** [comment]
Confirmed this. I believe it's something related to `isomorphic-style-loader`, which I'm in the process of removing on the `next` branch. However, there are some other significant breaking changes I'm planning on making before bumping the version, so it may take some time before I can get a fix out.
