### ISSUE TITLE
Double tap to zoom does not work

### ISSUE THREAD

**Issue by cmmartti** [frontend-collective/react-image-lightbox#113]
On touch screens in certain browsers, double tapping does not zoom images the way double clicking does:

- Firefox (Android and Windows): does not work
- Chrome (Android and Windows): does not work
- Samsung Internet on Android: does not work
- Edge: works
- IE11: works

Most end users will expect that double-tapping will zoom the image because that is the way nearly all image viewers with touch-enabled interfaces work (see the stock image viewer on Windows/iOS, for example).

In theory, this should be covered by the `onDoubleClick` event handler that is attached to the image div, but the touch handlers seem to prevent this from happening. Removing

````
onTouchStart={this.handleTouchStart}
````

from the `ril-outer` div confirms that double tap to zoom otherwise seems to works fine on Firefox, but there is no change in Chrome or Samsung Internet (pinch to zoom and swipe still work for some unknown-to-me reason, even without any of the touch handlers).

Different operating systems interpret double clicks slightly differently, and some systems such as Windows allow the user to change the double click speed. I don't know if all browsers actually respect that setting for taps, but I don't think it makes sense to implement double tap functionality ourselves if the `onDoubleClick` event can handle it.

However, I don't know the best way to fix this, even after looking at the code for several hours. Any thoughts?

---

On an unrelated note, at over 1800 lines this component is very large and as a result is fairly difficult to decipher. Perhaps some functionality should be broken off into separate components?

**Comment by Slapbox** [comment]
I think this needs to be handled in this function with a timer to listen for a second tap and programmatically zoom if it's a double tap.

https://github.com/frontend-collective/react-image-lightbox/blob/master/src/react-image-lightbox.js#L820-L826

@wuweiweiwu @fritz-c am I on the right track here?

**Comment by Shashank2406** [comment]
Any update on this ?

**Comment by Slapbox** [comment]
Nope. I think you could submit a PR that uses `setTimeout` to listen for two taps (clicks) in a row in some period, say 500ms, and leverage whatever function handles the zoom from there.

The "listening" would need to take place _maybe_ in this function: https://github.com/frontend-collective/react-image-lightbox/blob/master/src/react-image-lightbox.js#L866-L889

 I don't have time to investigate further unfortunately, but if anyone takes a crack at it I can provide support as far as analysis of the issue and trying to help troubleshoot.

**Comment by Shashank2406** [comment]
Fixed in my fork, also added some new props
https://github.com/Shashank2406/lightbox-react

**Comment by Slapbox** [comment]
@Shashank2406 very cool! I'm excited to give it a try!
