### ISSUE TITLE
Show multiple images together

### ISSUE THREAD

**Issue by bellgetlinks** [frontend-collective/react-image-lightbox#117]
I want to show multiple images it can to be a new feature? 
In my case I want to compare 2 images together by using this lib.

Thanks

**Comment by wuweiweiwu** [comment]
@bellgetlinks Do you mean side by side with each image taking up half the space?

I think if we want to add this feature, we'd want to add more layouts

**Comment by bellgetlinks** [comment]
Yes, Show side by side by seperate layout.

Maybe I could develop this feature :)

**Comment by wuweiweiwu** [comment]
@bellgetlinks That'll be awesome!
