### ISSUE TITLE
SSR support on v5.0.0

### ISSUE THREAD

**Issue by nnishimura** [frontend-collective/react-image-lightbox#118]
Using `react-image-lightbox@5.0.0` on non-browser env(e.g. SSR) throws `window is not defined` error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/Users/nnishimura/works/git/my-repo/node_modules/react-image-lightbox/dist/main.js:3:3)
``` 
https://cdn.jsdelivr.net/npm/react-image-lightbox@5.0.0/dist/main.js

This is due to webpack issue, https://github.com/webpack/webpack/issues/6522

**Comment by wuweiweiwu** [comment]
@nnishimura thanks for the catch!

**Comment by Arrvin** [comment]
@nnishimura hi i am new to this react. i am getting same issue as you posted. but i didn't getting what you telling about this. can you explain it for me. what i have to do at webpack?
thank you.

**Comment by nnishimura** [comment]
@Arrvin this issue only happens when you are using the latest version of `react-image-lightbox` (v5.0.0). So if you are on SSR app, you need to use v4.6.0 or below for now.  Or you can wait for the next version which will have the fix 👍

**Comment by Arrvin** [comment]
@nnishimura thank you

**Comment by jonkwheeler** [comment]
As @nnishimura mentioned, this only works on v4.6.0, not v5.0.0. Looks like something was added in PR #119 - Am I missing something to get SSR working on the latest version?

**Comment by mmarkelov** [comment]
If you want use the latest version with SSR you can do something like this:
```javascript
...
typeof window !== 'undefined' && <Lightbox/>
...
```
