### ISSUE TITLE
Redundant `alt` attribute

### ISSUE THREAD

**Issue by k1sul1** [frontend-collective/react-image-lightbox#124]
With this kind of "config", each image in the lightbox has an alt attribute with the value of "Image".

```javascript
<Lightbox
  mainSrc={images[index].src}
  nextSrc={images[(index + 1) % images.length].src}
  prevSrc={images[(index + images.length - 1) % images.length].src}
  imageCaption={images[index].caption}
  toolbarButtons={[
    <button key="fullscreen" onClick={this.enableFullscreen}>Fullscreen</button>,
  ]}
  onCloseRequest={onCloseRequest}
  onMovePrevRequest={() =>
    this.setState({
      index: (index + images.length - 1) % images.length,
    })
  }
  onMoveNextRequest={() =>
    this.setState({
      index: (index + 2) % images.length,
    })
  }
/>
```

This is actually worse than no alt attribute at all, as screen readers already point out that it's an image. We're using https://github.com/reactjs/react-a11y in development, and it throws some warnings saying exactly that. 

~~Quickly looking at the options, there doesn't seem to be an option to specify the alt attribute. There probably should be? It could fall back to imageCaption (if set), or not set the alt attribute at all.~~

Looking at the [source](https://github.com/frontend-collective/react-image-lightbox/blob/master/src/react-image-lightbox.js#L1384), the alt attribute is set from imageTitle option, but that also renders a `span.ril-toolbar__item__child.ril__toolbarItemChild`, that doesn't suit this use case, and has to be hidden using CSS.

That descriptive element doesn't seem very accessible either, but that's minor. Dedicated option for alt would be nice, is the point :slightly_smiling_face:

**Comment by amalitsky** [comment]
`alt` is also broken for cases when `imageTitle` is being passed as a node due to this piece of code:
```jsx
alt={
  typeof imageTitle === 'string' ? imageTitle : translate('Image')
}
```
