### ISSUE TITLE
Custom container / Not fullscreen

### ISSUE THREAD

**Issue by skizzo** [frontend-collective/react-image-lightbox#131]
Is there any way to show this marvelous component not on top of everything else, but in a custom container like a `div`?

**Comment by JulioC** [comment]
Try using:
```
            <Lightbox
                reactModalProps={{
                    appElement: document.querySelector("#root")
                }}
            />
```

**Comment by skizzo** [comment]
@JulioC thanks, but what is that supposed to accomplish?

**Comment by JulioC** [comment]
If I recall correctly, you are supposed to pass the element reference in
appElement. In the case of the code above, it would be element #root

**Comment by skizzo** [comment]
Unfortunately, this property doesn't change *anything* about the lightbox's appearance. `reactModalStyle` also doesn't do anything. Wondering if this component is even maintained still..
