### ISSUE TITLE
getOrigin issue within iFrames

### ISSUE THREAD

**Issue by sntk** [frontend-collective/react-image-lightbox#136]
# Reporting a Bug?
Yes.

https://github.com/frontend-collective/react-image-lightbox/blob/c9fcb5ba0c176ebae0cf8558bfb795a804a969ed/src/util.js#L35

# Requesting a Feature?
No.

I'm using this component inside a Chrome Extension (in an iframe), the document.referrer returns an empty string which throws a typeError

```
Uncaught TypeError: Cannot read property '1' of null
    at getOrigin (<anonymous>:1:58)
    at <anonymous>:1:35
```

Would it be possible to add a check for empty strings?
Repro: http://jsfiddle.net/czm0fqyv/1/

Much appreciated!

**Comment by sntk** [comment]
This may not be the most elegant solution, but perhaps

```const getOrigin = href => href.length ? href.match(/(.*\/\/.*?)(\/|$)/)[1] : null;```

**Comment by dtslvr** [comment]
Thanks for reporting, I have exactly the same issue inside my [Storybook](https://storybook.js.org) environment.

**Comment by came** [comment]
I have the same issue :(
