### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by alaatm** [frontend-collective/react-image-lightbox#164]
When using this in an RTL website and when the width of the image is larger than the window width, the `translate3d` css will position the image incorrectly offscren.

I suggest adding a rtl boolean property to the component to correct calculate the `x` argument of `translate3d`. Basically it just needs to be multiplied by -1.

Below image show the incorrectly positioned image:
![1](https://user-images.githubusercontent.com/2095803/51537708-54358c80-1e60-11e9-9c2c-b29e572f0c58.png)

When changing `translate3d(-297px, 0px, 0px)` to `translate3d(297px, 0px, 0px)` then the image will correctly be centered:
![2](https://user-images.githubusercontent.com/2095803/51537777-834bfe00-1e60-11e9-9bb0-cdadc9133249.png)

**Comment by mskashef** [comment]
I'm still facint this issue and it's not solved.
