### ISSUE TITLE
React 15.1 support

### ISSUE THREAD

**Issue by Jakku7** [frontend-collective/react-image-lightbox#169]
Is there a support for previous versions of React (15.1)? 

Every time I try to open lightbox modal I get:
"React__default.createRef is not a function"

Which basically states that version below 16 is not supported (createRef was introduced in v. 16). Is there any workaround?

**Comment by wuweiweiwu** [comment]
hi @Jakku7 I don't plan on supporting older versions of react. However, older versions of this library does.

Another option is instead using the old function refs. But I'd prefer us to stay current
