### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

### ISSUE THREAD

**Issue by csmolnar** [frontend-collective/react-image-lightbox#171]
Hi,

I get the following message in my browsers console recently:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

I have Chrome Version 73.0.3683.75 (Official Build) (64-bit).
It appears on both my application, on the Demo page or on the CodeSandbox example code.

This status report is about handling the mouse scroll inside the Chrome window.

Thanks!

**Comment by nonanonakeita** [comment]
Any idea?

**Comment by vlavlad** [comment]
Hi @fritz-c @wuweiweiwu, I have this issue for now too. This issue takes place for prod and dev build. Could you possibly check this issue and the pull request sent by @mmarkelov?

**Comment by famu1hundred** [comment]
+1 I still see this issue and I have chrome 75

**Comment by saundersdigital** [comment]
Are there plans to merge this anytime soon?
