### ISSUE TITLE
Add social media share buttons

### ISSUE THREAD

**Issue by alacroixAskin** [frontend-collective/react-image-lightbox#172]
Hello everyone,

I would like to display social media share buttons when the lightbox is open. I use the react-share extension for this.

But it doesn't works with option "toolbarButtons" or "imageCaption" or "imageTitle".

I tried : 
<Lightbox
  mainSrc={photo['photoGalleryFile']}
  toolbarButtons={<DisplayFacebookButton photo={photo['photoGalleryFile']}/>}
  onCloseRequest={() => this.setState({openLightboxMessageId: false})}
  reactModalStyle={{overlay: {zIndex: "1040"}}}
/>

Does anyone already tried this ?

Thanks for your help

**Comment by alacroixAskin** [comment]
Finally I successed to add them with toolbarButtons

**Comment by kamalarieff** [comment]
Hi @alacroixAskin, do you mind sharing the solution you had for this? I'm also stuck here.

**Comment by alacroixAskin** [comment]
@kamalarieff Oh yes sorry I did this :

`<Lightbox
                                            mainSrc={photo}
                                            toolbarButtons={[
                                                <FacebookShareButton url={photo} className={'socialShareButtons'}>
                                                    <FacebookIcon size={32} round/>
                                                </FacebookShareButton>,
                                                <TwitterShareButton url={photo} className={'socialShareButtons'}>
                                                    <TwitterIcon size={32} round/>
                                                </TwitterShareButton>,
                                                <WhatsappShareButton url={photo} className={'socialShareButtons'}>
                                                    <WhatsappIcon size={32} round/>
                                                </WhatsappShareButton>,
                                                <EmailShareButton url={photo} className={'socialShareButtons'}>
                                                    <EmailIcon size={32} round/>
                                                </EmailShareButton>
                                            ]}
                                            onCloseRequest={() => this.setState({openLightboxMessageId: false})}
                                            reactModalStyle={{overlay: {zIndex: "1040"}}}
                                        />`

Hope it helps
