### ISSUE TITLE
Hooks compatibility 

### ISSUE THREAD

**Issue by clintsearl** [frontend-collective/react-image-lightbox#173]
# Reporting a Bug?
Not sure if it's me or maybe a compatibility issue.  I have my button to change the state with hooks, however the Lightbox never pops up for me.
```const About=()=>{
    const [isOpen, setisOpen] = useState()
    return(          
            <img src={path} className="img-fluid"
            onClick={()=> setisOpen(true)}
            />
            <button onClick={()=> setisOpen(true)} value="hello">Hello</button>
            {isOpen && (
          <Lightbox
            mainSrc={path}     
            onCloseRequest={() =>setisOpen(false) }  
          />
        )}
```
- What's your use case? (Tell me about your application and what problem you're trying to solve.)
I'm using some MDBootstrap as well so maybe that's throwing things off...
 path is the name of my image

**Comment by mmarkelov** [comment]
@clintsearl it should work. Here is example with hooks:
[![Edit react-image-lightbox with hooks](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-wind-zsqp6?fontsize=14)
