### ISSUE TITLE
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

### ISSUE THREAD

**Issue by constantinpojoga** [frontend-collective/react-image-lightbox#187]
Hi, thank you for the great tool!
Wanted to ask if you can fix this issue: in Chrome I'm getting thousands of these messages, [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See See https://www.chromestatus.com/features/6662647093133312

Thank you

**Comment by dylangrandmont** [comment]
Looks like a duplicate of a fixed issue https://github.com/frontend-collective/react-image-lightbox/issues/171. **However** that fix has not been published yet.

I ran into this issue as well today on the latest `npm` package. Are there plans to cut a release with this fix in it?

**Comment by Paulus90** [comment]
Will this be fixed anytime soon? Errors are piling up in Chrome...

**Comment by online0227** [comment]
Is this fixed? I still get the error

**Comment by smenshikov** [comment]
Today is 2021! I still get the error

**Comment by AidenBurgess** [comment]
Still getting error

**Comment by liuhe2020** [comment]
Still getting error

**Comment by JoniRinta-Kahila** [comment]
Same error will continue in 2022!

**Comment by Jay-WKJun** [comment]
Still get same Errors in 2022!
