### ISSUE TITLE
[Safari iOS] Large Image is not rendered completely

### ISSUE THREAD

**Issue by fokoz** [frontend-collective/react-image-lightbox#188]
Large Image(3000x3000+) is not fully rendered when open `lightbox`, Often render about 50-70% of image height.
Desktop browsers work fine, it happens only in Safari browser in iOS.

npm version: 5.1
iOS: 12

**Comment by yeluoqiuzhi** [comment]
the same problem

**Comment by WookashWackomy** [comment]
I have experienced the same issue and have not been able to fix it.

**Comment by MaiconFilipiaki** [comment]
I have same problem, but only in IOS 13

**Comment by shadowgroundz** [comment]
In IOS 15 crash and reload

**Comment by sagardesai16** [comment]
> In IOS 15 crash and reload

Even i'm facing the same issue. Any fix for this?

**Comment by rakeshb-iprogrammer** [comment]
I too faced this issue, it is due higher image resolution.
Light house on iOS Safari is not able to handle image with higher image resolution (might be memory leak due to which browser crash and reload), have handled this by reducing image resolution.

Hope this help someone!
