### ISSUE TITLE
Convert to hooks

### ISSUE THREAD

**Issue by agusterodin** [frontend-collective/react-image-lightbox#243]
This library could definitely benefit from being converted over to hooks, especially given the unsafe methods it uses. I would love to help implement if this hasn't already been started.

Also, I feel like this library could greatly benefit from separating logic out across more files. Most of the logic is in one file. What is the reasoning behind this? Again, I would love to help if needed.

**Comment by agusterodin** [comment]
Otherwise would anybody who started/maintans this library care if I created a fork and rebranded it a little bit? I would obviously credit to everyone involved with this library.

React is way too popular of a platform not to have a lightbox library that is actively developed/maintained. This is the best library I have encountered so far. Converting to hooks and restructuring/seperating things out into multiple files (seperation of concerns is really needed here) would most definitely encourage more contributions from non-maintainers and help a lot with maintainability.

**Comment by constantinpojoga** [comment]
It's a great library but with React moving so fast, and this library requires some attention: deprecated methods, a lot of console warnings, etc. 
I'm also available to contribute/rewrite it. Please let me know if you need some help.

**Comment by crobinson42** [comment]
Considering the amount of open PR's there's some stagnancy in this lib - why not just get a fork started and if no feedback or effort is shown from the owner/author of this lib, publish as a new package 👍

**Comment by constantinpojoga** [comment]
I can give it a try this weekend. Like @agusterodin mentioned, I can give the author the credit.

**Comment by AshotN** [comment]
So did anyone create a maintained fork?
