### ISSUE TITLE
iPhone swipe interaction is very poor

### ISSUE THREAD

**Issue by pravinweb** [frontend-collective/react-image-lightbox#256]
Thanks for this great plugin,

I tested it here - https://frontend-collective.github.io/react-image-lightbox/

I tried to verify this plugin on iPhone 7 plus Safari but swipe touch does not work well, and interaction is very poor. User need to swipe more than once to goto next image. also when user swipe outside image it does not work. transition is not smooth at all.

Does any facing same issue? Is there any resolution for smooth transition ?

Thanks
Pravin

**Comment by konstantinschuette** [comment]
I can agree. It's at least nice to have a sliding option, but it provides a very bad UX. But looking at the date, when you started this post, the project doesn't seem to be maintained
