### ISSUE TITLE
Option to change the loading component

### ISSUE THREAD

**Issue by ybrodsky** [frontend-collective/react-image-lightbox#275]
When an image is being loaded a css spinner is show. [Here I think](https://github.com/frontend-collective/react-image-lightbox/blob/master/src/react-image-lightbox.js#L1349)

Add an option to pass a component to show instead

```
<Lightbox
  ...
  renderLoading={<MyCustomLoading />}
/>
```

Also, lots of PR. Is this being actively maintained?

**Comment by SeinopSys** [comment]
Seems like this was done in  #385
