### ISSUE TITLE
setAppElement from react-modal

### ISSUE THREAD

**Issue by itviventura** [frontend-collective/react-image-lightbox#30]
Hi everybody, 

I have integrated react-image-lightbox however I have the following error message: "Uncaught Error: react-modal: You must set an element with `Modal.setAppElement(el)` to make this accessible"

Anyone know how could I fix it? I am using "react-modal": "^1.3.0" dependency.

Thanks a lot for your help.

**Comment by fritz-c** [comment]
This sounds more like a react-modal usage issue, but could you provide some sample code anyway?

**Comment by itviventura** [comment]
Hi Fritz-c,

Do you know if is enough to work with var Lightbox = require('react-image-lightbox'); or is necessary to use create any instance of react-modal?

I have just the following code:


var Lightbox = require('react-image-lightbox');
     var images = [
            'https://d2ji2mue1p384z.cloudfront.net/img/2048x1536/196854.jpg',
            'https://d2ji2mue1p384z.cloudfront.net/img/2048x1536/196856.jpg',
        ];
        
window.ImageLightboxCollage = React.createClass({
    getInitialState: function() {
        return {
            index: 0,
            isOpen: false
        };
    },
    openLightbox: function() {
        this.setState({ isOpen: true });
    },
    closeLightbox: function() {
        this.setState({ isOpen: false });
    },
    moveNext: function() {
        this.setState({ index: (this.state.index + 1) % images.length });
    },
    movePrev: function() {
        this.setState({ index: (this.state.index + images.length - 1) % images.length });
    },
    render: function() {


        var lightbox = '';
        if (this.state.isOpen) {
            lightbox = (
                <Lightbox
                    mainSrc={images[this.state.index]}
                    nextSrc={images[(this.state.index + 1) % images.length]}
                    prevSrc={images[(this.state.index + images.length - 1) % images.length]}

                    onCloseRequest={this.closeLightbox}
                    onMovePrevRequest={this.movePrev}
                    onMoveNextRequest={this.moveNext}
                />
            );
        }

        return (
            <div>
                <button type="button" onClick={this.openLightbox}>Open Lightbox</button>
                {lightbox}
            </div>
        );
    }
});


ReactDOM.render(React.createElement(ImageLightboxCollage, {params: params}), document.getElementById('main-header-container'));

Thanks a lot

**Comment by fritz-c** [comment]
Sorry for the delayed reply. Were you able to figure this out?

To answer your question, you don't need to add your own `react-modal` instance to use the lightbox. As far as I can tell from your code, it should be working.

**Comment by pinya** [comment]
More details on this issue https://github.com/reactjs/react-modal/issues/133

I worked around it by adding

```js
import Modal from 'react-modal';
```

```js
   componentWillMount() {
        Modal.setAppElement('body');
    }
```


Full example

```jsx
import React, {Component} from 'react';
import Lightbox from 'react-image-lightbox';
import Modal from 'react-modal';

const images = [
    '//placekitten.com/1500/500',
    '//placekitten.com/4000/3000',
    '//placekitten.com/800/1200',
    '//placekitten.com/1500/1500'
];

export default class Gallery extends Component {
    constructor(props) {
        super(props);

        this.state = {
            photoIndex: 0,
            isOpen: false
        };
    }

    componentWillMount() {
        Modal.setAppElement('body');
    }

    render() {
        const {
            photoIndex,
            isOpen
        } = this.state;

        return (
            <div>
                <button
                    type="button"
                    onClick={() => this.setState({isOpen: true})}
                >
                    Open Lightbox
                </button>

                {isOpen &&
                <Lightbox
                    mainSrc={images[photoIndex]}
                    nextSrc={images[(photoIndex + 1) % images.length]}
                    prevSrc={images[(photoIndex + images.length - 1) % images.length]}

                    onCloseRequest={() => this.setState({isOpen: false})}
                    onMovePrevRequest={() => this.setState({
                        photoIndex: (photoIndex + images.length - 1) % images.length,
                    })}
                    onMoveNextRequest={() => this.setState({
                        photoIndex: (photoIndex + 1) % images.length,
                    })}
                />
                }
            </div>
        );
    }
}
```

**Comment by malroc** [comment]
Same issue.
This is a known bug in `react-modal`: https://github.com/reactjs/react-modal/issues/133
The workaround helped, but since `react-image-lightbox` relies on `react-modal` and calls it implicitly, it isn't just a "react-modal usage issue", it is a `react-image-lightbox` issue too.
