### ISSUE TITLE
animationOnKeyInput does not work

### ISSUE THREAD

**Issue by pvernekar-cci** [frontend-collective/react-image-lightbox#309]
`animationOnKeyInput={true}` this doesn't change an image based on the keyboard prev and next click.

@c00kiemon5ter

**Comment by pvernekar-cci** [comment]
Any update on this?
@c00kiemon5ter @webcarrot @lexich @ohtake

**Comment by irfanDC** [comment]
@pvernekar-cci did you resolved it ? I am facing same issue

**Comment by pvernekar-cci** [comment]
@irfanDC no I didn't find any solution. Let me know if you find anything.

**Comment by pvernekar-cci** [comment]
It works on the sandbox example but if I use the same code then keyboard next/prev keys not working.
