### ISSUE TITLE
Please run `npx react-codemod rename-unsafe-lifecycles` in your project source folder to rename all deprecated lifecycles

### ISSUE THREAD

**Issue by bfeliz** [frontend-collective/react-image-lightbox#335]
We are getting the following two warnings, which look like a simple fix by running 'npx react-codemod rename-unsafe-lifecycles' in the source folder. Thank you for a wonderful npm package, we love it!

Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactImageLightbox
printWarning @ react-dom.development.js:88
warn @ react-dom.development.js:51
dll_0fb095e325d7ebf261c3../node_modules/react-dom/cjs/react-dom.development.js.ReactStrictModeWarnings.flushPendingUnsafeLifecycleWarnings @ react-dom.development.js:11393
flushRenderPhaseStrictModeWarningsInDEV @ react-dom.development.js:23143
commitRootImpl @ react-dom.development.js:22427
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11061
commitRoot @ react-dom.development.js:22412
finishSyncRender @ react-dom.development.js:21838
performSyncWorkOnRoot @ react-dom.development.js:21824
(anonymous) @ react-dom.development.js:11111
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11061
flushSyncCallbackQueueImpl @ react-dom.development.js:11106
flushSyncCallbackQueue @ react-dom.development.js:11094
discreteUpdates$1 @ react-dom.development.js:21924
discreteUpdates @ react-dom.development.js:1071
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:88 

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: ReactImageLightbox

**Comment by marnixhoh** [comment]
Is there any progress on this? It seems like this makes it unsafe to upgrade to React 17...

**Comment by fritz-c** [comment]
Should be fixed now. Thank you.

**Comment by JAMESK28** [comment]
Please did this 'npx react-codemod rename-unsafe-lifecycles' solved the issue
