### ISSUE TITLE
Decrease main lightbox image

### ISSUE THREAD

**Issue by douglasrcjames** [frontend-collective/react-image-lightbox#358]
I am attempting to decrease the main image size but just a bit, specifically just the height of the toolbars (70px looks like) because I am showing screenshots of websites and don't want the toolbar to be covering up the header part at all. I have messed around a bit with the CSS and looks like the sizing of the image is dynamic based on the `transform()` method. 

This is the solution I have now: 
```
.ril__inner {
    margin-top: 75px;
}
```

but this causes the whole image to be pushed down and now the footer of every screenshot is totally hidden. Does anyone have a solution for this?

![image](https://user-images.githubusercontent.com/22306305/99862728-a83e5480-2b4f-11eb-9542-4221a17db9ae.png)

**Comment by occurance-now** [comment]
I ran into this issue yesterday as well. I solved my problem by turning the opacity of the toolbar to 0.0. I know its a cheap trick but it worked for me. 

.ril__toolbar {
  background-color: rgba(0, 0, 0, 0.0);
}
