### ISSUE TITLE
can i place rotate button ??

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [frontend-collective/react-image-lightbox#41]
hi,
i want to put rotate button with zoom buttons.
i able to place that button but how can i handle that rotate button click?

**Comment by fritz-c** [comment]
I'm not sure. The library relies on the height / width of the original image, so it would be difficult to change it using just css. What do you want to rotate the images for?

**Comment by nilaybrahmbhatt** [comment]
i want rotate left and right button same as zoom.
that rotate image appropriately left and right

**Comment by fritz-c** [comment]
I don't have support for this in this library, but you're welcome to add it.

The width and height of the original image are referenced from here:
https://github.com/fritz-c/react-image-lightbox/blob/da13c43d110df1d2775177c35fb14f3a5b66b2cc/src/react-image-lightbox.js#L373-L379
You'd have to instead use your rotation information to determine the actual height and width after rotation.

And you'd have to add the necessary style info to the img tags here:
https://github.com/fritz-c/react-image-lightbox/blob/da13c43d110df1d2775177c35fb14f3a5b66b2cc/src/react-image-lightbox.js#L1317-L1346

**Comment by MayankShukla5031** [comment]
@nilaybrahmbhatt  yes you can put the rotate icon in lightbox to rotate the current image, i am using light box for my current project and we achieve the rotate feature, try this:

`const BillAction  =  [
			
			<i className="material-icons" onClick={this._rotateImage.bind(this, 'right')}>rotate_left</i>,
			<i className="material-icons" onClick={this._rotateImage.bind(this, 'left')}>rotate_right</i>,
    	];`

use this property of LightBox:
` toolbarButtons={BillAction}`

Define this function to rotate the image:

`_rotateImage(type){

    	if(type == 'left'){
    		let angle = (this.state.rotationAngle + 90) % 360;
    		this.setState({rotationAngle : angle});
    		document.getElementsByClassName('image-current')[0].style.transform = `rotate(${angle}deg)`;
    	}else{
    		let angle = (this.state.rotationAngle + 360 - 90) % 360;
    		this.setState({rotationAngle : angle});
    		document.getElementsByClassName('image-current')[0].style.transform = `rotate(${angle}deg)`;
    	}
    }`

**Comment by MayankShukla5031** [comment]
I am trying to add this as a feature like zoom.

**Comment by trentonsnyder** [comment]
Was anyone able to figure out this rotate enhancement? I just found out it's absolutely necessary for the project I'm on.

**Comment by trentonsnyder** [comment]
@MayankShukla5031 Thanks for posting your solution. It works great!

**Comment by rajatgang786** [comment]
Cannot read property 'style' of undefined

document.getElementsByClassName('image-current')[0].style.transform = `rotate(${angle}deg)`;

**Comment by sh19900816** [comment]
zoom and rotate are together; when you rotate this image, and then zoom it, it will go back to the original angle? Are you encounter this problem ?

**Comment by snehaaaa** [comment]
After zoom when you rotate this image it will go back to the original angle in react lightbox.Is there any way to solve this.I am using react-image-lightbox;
