### ISSUE TITLE
usage of deprecated life cycle methods, getting warnings of the same 

### ISSUE THREAD

**Issue by jinojacob15** [frontend-collective/react-image-lightbox#429]
Please migrate to react hooks so that we can avoid these warnings 
![DeepinScreenshot_select-area_20210528224213](https://user-images.githubusercontent.com/69616951/120020432-50553e80-c007-11eb-86fe-dac04984c0e8.png)

**Comment by fritz-c** [comment]
Should be resolved now, thanks to #227

**Comment by jinojacob15** [comment]
> Should be resolved now, thanks to #227
@fritz-c  Do i need to update the package ? or do something else ?

**Comment by fritz-c** [comment]
I released version 5.1.3 with the fixes.

**Comment by jinojacob15** [comment]
> I released version 5.1.3 with the fixes.

Thanks @fritz-c , it works now
