### ISSUE TITLE
image thumbnails

### ISSUE THREAD

**Issue by sandervanhooft** [frontend-collective/react-image-lightbox#44]
Hi @fritz-c,

What's the purpose of the `mainSrcThumbnail`, `nextSrcThumbnail` and `previousSrcThumbnail`?

It's noted in the `readme.md`, but I don't understand.

Kind regards,

Sander

**Comment by fritz-c** [comment]
The assumption is that the image referenced by `mainSrc` could be very large. In that case, we first show the image at a lower resolution via the faster-loading `mainSrcThumbnail`.

Now that you mention it, I don't really explain that in the README. I'll fix it.

**Comment by fritz-c** [comment]
Fixed. Does this commit look good? https://github.com/fritz-c/react-image-lightbox/commit/4629f9ea9ba030fe8e63d7b4fe5f79436db64797
