### ISSUE TITLE
Why not use CSS Module for 'close' class name?

### ISSUE THREAD

**Issue by giiska** [frontend-collective/react-image-lightbox#45]
Good work for developing this with CSS Module, but I find there is still a class name `.close` is not in CSS Module style. It's conflicting with Bootstrap css in my project.

```js
className={'close ril-close ril-toolbar__item__child' +
```

**Comment by fritz-c** [comment]
The css modules setup I originally used output class names with a random hash at the end, so it would have been impossible to style them based on the class name. The first time I considered this problem, I decided to add generic class names (i.e., `close`) so the users could style it themselves, but unfortunately I didn't consider that too-generic names like `close` would cause collisions with other libraries.

I am planning to delete the generic names in v4.0, but I have another CSS-related fix that would also justify a major version bump - getting rid of `style-loader`. You can find more details on that here: https://github.com/fritz-c/react-image-lightbox/issues/28, and a temporary workaround for the close button issue here: https://github.com/fritz-c/react-image-lightbox/issues/33
