### ISSUE TITLE
Allow background color for image to be set

### ISSUE THREAD

**Issue by fpayer** [frontend-collective/react-image-lightbox#49]
There doesn't seem to be a way to specify the background color for the image inside the lightbox. This would be helpful so that images with a transparent background could have a background to contrast to.

**Comment by oillamp** [comment]
+1

**Comment by jeansebbaklouti** [comment]
Hello, 

you can do something like that for the moment:

`<Lightbox
      mainSrc={imageUrl}
      alt={alt}
      onCloseRequest={() => setIsOpen(false)}
      wrapperClassName='custom_modal_image'
    />`

and in ccs file:

`.custom_modal_image {
	background-color: #575756;
}`

i hope that help,
Jean-Sébastien
