### ISSUE TITLE
Loading icon gets stuck in React 18 dev mode

### ISSUE THREAD

**Issue by igordanchenko** [frontend-collective/react-image-lightbox#589]
I ran into this issue in React 18 app using strict mode.

The lightbox never shows the first image, but instead, it keeps showing a loading icon. The images start showing fine only after I click the previous/next buttons.

![Screen Shot 2022-03-31 at 7 28 43 PM](https://user-images.githubusercontent.com/64441155/161165963-e10bee61-62b3-4fce-8923-feeffe5ac0ab.png)

Demo: https://codesandbox.io/s/github/igordanchenko/react-photo-album/tree/v1.12.0/examples/lightbox

Steps to reproduce:
1. Open the above link
2. Click any image

This issue is related to the following change in React 18:

> React 18 introduces a new development-only check to Strict Mode. This new check will automatically unmount and remount every component, whenever a component mounts for the first time, restoring the previous state on the second mount.

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode

While this bug is currently visible only in dev mode, it highlights that similar issues may occur in production in the future.

**Comment by syum-akhlaque** [comment]
Any update on this issue?

**Comment by jongjunpark** [comment]
same issue

**Comment by cruzlutor** [comment]
Same issue, if you resize the window the current image appears

**Comment by dsdsharma** [comment]
Having the same issue

**Comment by kahirokunn** [comment]
same issue

**Comment by tarasmelnychuk** [comment]
Found temp hack to solve the problem (tested on chrome only):

```tsx
{lightBoxImage && (
        <Lightbox
          mainSrc={lightBoxImage}
          onImageLoad={() => {
            window.dispatchEvent(new Event('resize'));
          }}
          onCloseRequest={() => setLightBoxImage(null)}
        />
      )}
```

**Comment by lvilasboas** [comment]
Same problem here, but at least @ihappycoder 's hacky fix worked

**Comment by igordanchenko** [comment]
If anyone is looking for an alternative to react-image-lightbox, here is the recently released lightbox library - [yet-another-react-lightbox](https://github.com/igordanchenko/yet-another-react-lightbox). All feedback is welcome.

**Comment by ajitstark** [comment]
> Same issue, if you resize the window the current image appears

same here

**Comment by rpin-01** [comment]
Same issue

**Comment by FStriewski** [comment]
Same, please fix

**Comment by Fidia-e** [comment]
https://www.npmjs.com/package/react-18-image-lightbox

**Comment by larinius** [comment]
I have this issue on react-18-image-lightbox  and original versions.

With "hacky fix" - issue gone, only have little longer loading time.

**Comment by Mokesh-off** [comment]
> https://www.npmjs.com/package/react-18-image-lightbox

Is this a separate package for react-18? looks like the readme is not updated properly
https://www.npmjs.com/package/react-18-image-lightbox?activeTab=readme

**Comment by mleister97** [comment]
Looks like the library frontend-collective/react-image-lightbox will not be maintained anymore. Really a pity.

**Comment by mostofanobi** [comment]
[ihappycoder](https://github.com/ihappycoder) THANKS A LOT❤️ You saved my life 😘

**Comment by Pha1Huynh** [comment]
Work with me, node v18.2.0, thank you.

**Comment by cescoferraro** [comment]
`onImageLoad={() => window.dispatchEvent(new Event("resize"))}`


fixed it for me
