### ISSUE TITLE
Dynamic <canvas> support

### ISSUE THREAD

**Issue by zslabs** [frontend-collective/react-image-lightbox#61]
Hi all!
I'm using [PDF.js](https://mozilla.github.io/pdf.js/) which in my implementation, returns a `<canvas>` element for each page of the PDF on request. Does this library support showing dynamically generated canvas images? Wanted to check before I go diving in as it's a bit outside of the normal examples. Thanks!

**Comment by Martin-Pitt** [comment]
Canvas support would be cool, and would be highly preferred to avoid memory duplication & performance issues. (Large retina images on mobile)

An alternative however you could use right now @zslabs is using Object URLs:
https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications#Example_Using_object_URLs_to_display_images

But you might see perf. issues on underpowered mobile devices with high-res screens generally with any method involving having to make a copy of the canvas, from somewhat efficient (File/Blob to Object URLs) to worse (format conversion), and horrific (Data URI).
