### ISSUE TITLE
Loading circle/Spinner customization

### ISSUE THREAD

**Issue by ray-su** [frontend-collective/react-image-lightbox#63]
Hello! Thank you for this great package.
Is it possible to add Loading circle/Spinner customization to it?

**Comment by kaizenberg** [comment]
@ray-su did you can add a custom image?

**Comment by 3nvi** [comment]
Any progress on that? From my perspective i'd love to be able to provide a react element as a custom loader. Like so:

```
<Lightbox
  {...otherProps}
  spinner={<MyCustomLoader />}
/>
```

**Comment by fritz-c** [comment]
This is a good candidate for a pull request.

**Comment by mik639** [comment]
Hi guys, I have pr for this :) #125

**Comment by borisrorsvort** [comment]
@wuweiweiwu @fritz-c Any update on this? Can you tell us what to do/expect?

**Comment by SeinopSys** [comment]
Seems like this was implemented in #385 but the TypeScript type definitions weren't updated, so attempting to use the `loader` property results in a type error.

**Comment by ghost** [comment]
Hello @SeinopSys,

Can you explain a bit more the issue? When I try to implement a custom loader component, by using the loader={<ComponentName/>}, I get no error at all. `<Lightbox... loader={<Test/>}/>`

With my test component being:

`const Test = () => {
    return (
      <div style={{...}}>Loading...</div>
    );
}`

Result I get:
<img width="1365" alt="Screen Shot 2021-09-17 at 9 45 48 AM" src="https://user-images.githubusercontent.com/59252693/133793056-dde9a0d2-a9dc-4310-86c9-472789fabd5e.png">

**Comment by SeinopSys** [comment]
That's not TypeScript though. I created a CodeSandbox link which shows the issue: https://codesandbox.io/s/react-image-lightbox-typescript-error-cn3hw?file=/src/LightboxExample.tsx

The `loader` prop is not recognized by TypeScript due to that property missing from the interface inside `index.d.ts` in the root of the project.
