### ISSUE TITLE
Image not loading on launch when React.StrictMode is enabled.

### ISSUE THREAD

**Issue by dmrkosterit** [frontend-collective/react-image-lightbox#672]
When the app is wrapped around in StrictMode like
root.render(
  <React.StrictMode>
    < App  />
  </React.StrictMode>
);

The lightbox gets stuck on the spinner until the image changes or the zoom-in button clicks.

**Comment by quangtho2910** [comment]
I got the same problem too!

**Comment by MrScX** [comment]
Same here. Any updates on this?

**Comment by jelizarovas** [comment]
Same here. Was wrapping my head around why it wouldn't load.

Lightbox itself loads, presing next or forward loads the images, zooming in also shows the images. Just initially stuck on loop.

**Comment by theutkarshsoni** [comment]
Same problem. Any updates?

I used the below temp hack and it worked for me.

https://github.com/frontend-collective/react-image-lightbox/issues/589#issuecomment-1159723673

Thanks @ihappycoder

**Comment by BozidarSiljanoski** [comment]
This is connected to https://github.com/reactjs/react-modal/issues/808 this issue on react-modal

**Comment by mleister97** [comment]
Seems like the lib is no longer maintained. Really sad...
