### ISSUE TITLE
React 18 not supported.

### ISSUE THREAD

**Issue by Mokesh-off** [frontend-collective/react-image-lightbox#688]
Steps to reproduce:
With React 18, npm i react-image-lightbox

Expected:
Successful installation

Actual:
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x || 17.x" from react-image-lightbox@5.1.4

**Comment by tirajetw** [comment]
me too

**Comment by Eng-Fouad** [comment]
Try with `--force` option.

**Comment by ahmadtariqf** [comment]
is there any other solution rather than using `--force`

**Comment by aaroncrawford** [comment]
No, I think this library has been abandoned unfortunately.  @fritz-c would be able to confirm/deny.

You can use `--force` to install and it mostly works - issues with StrictMode, see #672 for issue with initial loading in case you run into it.
