### ISSUE TITLE
Pass this.props.className to className?

### ISSUE THREAD

**Issue by ooloth** [frontend-collective/react-image-lightbox#86]
Great component!

It doesn't seem to work with styled-components, however... 

All that is needed to make react-image-lightbox lightbox compatible with styled-components is for react-image-lightbox to pass `this.props.className` to `className` (see [this](https://www.styled-components.com/docs/basics#styling-any-components), [this](https://www.styled-components.com/docs/advanced#existing-css) and [this](https://github.com/styled-components/styled-components/issues/1086)).

Is this a tweak that could be added?

**Comment by bastoune** [comment]
+1
