### ISSUE TITLE
Use srcset and sizes attributes?

### ISSUE THREAD

**Issue by ooloth** [frontend-collective/react-image-lightbox#87]
Is it possible to use responsive image markup (`srcset` and `sizes`) with react-image-lightbox?

I'd like to avoid hard-coding a single mainSrc image file to be used on every screen size... Is there a way to dynamically select the mainSrc image based on the viewport width?

**Comment by Max-Zviagintsev** [comment]
Sadly, I didn't find this valuable feature either.

**Comment by mhp-borisbojic** [comment]
I need that feature, too - do be able to display normal / retina images. This markup would be better:

`<img src="default.jpg" srcset="default.jpg 1x, default-retina.jpg 2x">`

**Comment by chaddjohnson** [comment]
This would be a key, useful feature.

**Comment by JackHowa** [comment]
Yep definitely -- same with me

**Comment by JackHowa** [comment]
Looking into this. It looks like there's some styles transform the image dynamically. 

with transform css in image
![Screen Shot 2020-05-13 at 8 20 48 PM](https://user-images.githubusercontent.com/5950956/81882219-c94a3b00-9557-11ea-8296-121b76a5fc15.png)

without css transform. at least showing the image at actual size
![Screen Shot 2020-05-13 at 8 20 57 PM](https://user-images.githubusercontent.com/5950956/81882215-c7807780-9557-11ea-8970-ac0ed2608648.png)

Basic image passing in being mocked. Let me know if you have any goals for how you'd want to pass in the srcSet, currently thinking: 

```
  // [ { intrinsicSize: '100w', imageUrl: 'https://image.jpg }]
  mainSrcSet: PropTypes.array,
```

https://github.com/JackHowa/react-image-lightbox/tree/ISSUE-87-image-src-set
