### ISSUE TITLE
Error when build to production

### ISSUE THREAD

**Issue by tuan072090** [frontend-collective/react-image-lightbox#88]
"webpack -d --progress" is fine but "webpack -p --progress" cause this error, please check the screenshot below

![image](https://user-images.githubusercontent.com/450893/32486092-319af9fa-c3d8-11e7-8ddb-72a25e2f6b04.png)

Thank you.

**Comment by zslabs** [comment]
We're getting this as well. I'm using `create-react-app` so nothing really out of the ordinary with the Webpack prod setup. I've found a few issues like [this one](https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-288001933) that appears to be similar, but the options I've looked into have not helped. It's definitely something in the prod webpack config, as dev works fine. 

I know that would potentially mean it's something outside of this library, but this is the only package that's giving us trouble, so reaching out to see if we have any ideas. Thanks!

**Comment by yzzhuo** [comment]
I update my webpack from version2 to version3 to fix this error.

**Comment by sean-stanley** [comment]
This issue seemed to not occur when I compiled using node version 9.x but occurred compiling with node 8.6.0 which my production environment used. Switching to webpack 3 was not enough on it's own to resolve this for me.

**Comment by fritz-c** [comment]
I think adding comparisons: false to your UglifyJS config, as seen here
https://github.com/facebookincubator/create-react-app/pull/2379/files
works as a temporary workaround. This is an issue with incompatibility between Webpack and UglifyJS's behavior, so I can only wait and see in the meantime. UglifyJS is necessary to remove dead code from the bundle.

**Comment by pietrofxq** [comment]
I found a workaround. Since the issue is with the -p webpack flag; it can be solved by removing this flag and running webpack with NODE_ENV=production set.

**Comment by ViswanathLekshmanan** [comment]
Using webpack 3.10.0 and Node v9.11.1 . This doesn't work
